version: 2
jobs:
    build:
        working_directory: ~/tmp
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
                      - "v2-deps-{{ .Branch }}-"
                      - v2-deps-
            - run:
                  name: Set up dependencies
                  command: npm ci
            - save_cache:
                  key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
                  paths:
                      - ~/.npm
                      - ~/.cache
            - run:
                  name: Build
                  command: npm run build
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - .cache
                      - tmp
    test1:
        working_directory: ~/tmp
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Start dev server and run Cypress tests
                  command: npm run cy:ci:es
            - store_artifacts:
                  path: /root/project/cypress/screenshots
    test2:
        working_directory: ~/tmp
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Start dev server and run Cypress tests
                  command: npm run cy:ci:iife
            - store_artifacts:
                  path: /root/project/cypress/screenshots
    test3:
        working_directory: ~/tmp
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Start dev server and run Cypress tests
                  command: npm run cy:ci:svelte
            - store_artifacts:
                  path: /root/project/cypress/screenshots

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test1:
                  requires:
                      - build
            - test2:
                  requires:
                      - build
            - test3:
                  requires:
                      - build
