version: 2
jobs:
    build:
        docker:
            - image: cypress/base:10
              environment:
                  ## this enables colors in the output
                  TERM: xterm
        steps:
            - checkout
            - run:
                  name: Set up dependencies
                  command: npm install
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Start dev server then run Cypress tests
                  command: npm run test
