version: 2
jobs:
    build:
        docker:
            - image: cypress/base:10
              environment:
                  ## this enables colors in the output
                  TERM: xterm
        steps:
            - checkout
            - run: echo "A first hello"
