version: 2
jobs:
    build:
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - checkout
            - run:
                  name: Set up dependencies
                  command: npm install
            - run:
                  name: Build
                  command: npm run build
    test1:
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - run:
                  name: Start dev server then run Cypress tests
                  command: npm run cy:ci:es
            - store_artifacts:
                  path: /root/project/cypress/screenshots
    test2:
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - run:
                  name: Start dev server then run Cypress tests
                  command: npm run cy:ci:iife
            - store_artifacts:
                  path: /root/project/cypress/screenshots
    test3:
        docker:
            - image: cypress/base:14.17.0
              environment:
                  TERM: xterm
        steps:
            - run:
                  name: Start dev server then run Cypress tests
                  command: npm run cy:ci:svelte
            - store_artifacts:
                  path: /root/project/cypress/screenshots

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test1:
                  requires:
                      - build
            - test2:
                  requires:
                      - build
            - test3:
                  requires:
                      - build
